---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: mysql-operator
      version: ^2.0.0
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
