---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mysql-operator
spec:
  chart: mysql-operator
  version: ^2.0.0
  repo: https://mysql.github.io/mysql-operator/
  targetNamespace: mysql-operator
