---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - composable-clusterissuers.yaml
  - helmrelease.yaml
  - namespace.yaml
  - rbac.yaml
  - sealedsecret-email.yaml
