apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: letsencrypt-email
  namespace: cert-manager
spec:
  encryptedData:
    # Will be overwritten in overlay
    email: ""
  template:
    metadata:
      creationTimestamp: null
      name: letsencrypt-email
      namespace: cert-manager
