---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: db-operator

resources:
  - composable-mariadb-admin-credentials.yaml
  - dbinstance.yaml
  - helmchart.yaml
  - namespace.yaml
  - rbac.yaml
