---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-admin-credentials
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    # resourceNames: ["mysql-admin-credentials"] # Doesn't seem to work with resourceNames :(
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: composable-mysql-admin-credentials
subjects:
  - kind: ServiceAccount
    name: composable-controller-manager
    namespace: composable-system
roleRef:
  kind: Role
  name: mysql-admin-credentials
  apiGroup: rbac.authorization.k8s.io
