---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: nextcloud-helmchart
spec:
  template:
    apiVersion: "helm.cattle.io/v1"
    kind: HelmChart
    metadata:
      name: nextcloud
    spec:
      chart: nextcloud
      repo: https://nextcloud.github.io/helm/
      version: <4.0.0
      targetNamespace: nextcloud
      set:
        externalDatabase.enabled: "true"
        externalDatabase.type: mysql
        externalDatabase.existingSecret.enabled: "true"
        externalDatabase.host: "main-db.mysql.svc.cluster.local:3306"
        externalDatabase.existingSecret.secretName: db-credentials
        externalDatabase.existingSecret.usernameKey: USER
        externalDatabase.existingSecret.passwordKey: PASSWORD
        externalDatabase.database:
          getValueFrom:
            kind: Secret
            name: db-credentials
            path: "{.data.DB}"
            format-transformers:
              - Base64ToString
        internalDatabase.enabled: "false"
        persistence.enabled: "true"
        persistence.nextcloudData.enabled: "true"
