---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: composable-nextcloud
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mariadb-credentials"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.cattle.io"]
    resources: ["helmcharts"]
    # resourceNames: ["nextcloud"] # Doesn't seem to work with resourceNames :(
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: composable-nextcloud
subjects:
  - kind: ServiceAccount
    name: composable-controller-manager
    namespace: composable-system
roleRef:
  kind: Role
  name: composable-nextcloud
  apiGroup: rbac.authorization.k8s.io
