---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql

resources:
  - innodbcluster.yaml
  - namespace.yaml
  - pvc-bind-job.yaml
  - pvc-main-db-backups.yaml
  - rbac.yaml
  - sealedsecret.yaml
