---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8up
spec:
  interval: 1h
  chart:
    spec:
      chart: k8up
      version: <5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values: {}
