---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.1.201
    hooks:
      - id: checkov
        args: [-d .]
  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
    rev: v0.1.0
    hooks:
      - id: k8svalidate
        files: .yaml$
  # Will care about these later
  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.27.1
  #   hooks:
  #     - id: yamllint
  #       args: [-c=.yamllint]
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.3.0
  #   hooks:
  #     - id: detect-secrets
  # - repo: https://github.com/stackrox/kube-linter
  #   rev: v0.4.0
  #   hooks:
  #     - id: kube-linter-docker
