---
repos:
  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
    rev: v0.1.0
    hooks:
      - id: k8svalidate
        files: .yaml$
  - repo: https://github.com/stackrox/kube-linter
    rev: 0.5.0
    hooks:
      - id: kube-linter-docker
        args: ["lint"]
