---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patchesStrategicMerge:
  - cert-manager/patch-sealed-secret-email.yaml
  - mysql/patch-sealed-secret.yaml
  - grafana-agent/patch-sealed-secret.yaml
