---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  # Add proper cluster label to Grafana data
  - patch: |-
      - op: replace
        path: /spec/clients/0/externalLabels/cluster
        value: "develop"
    target:
      kind: LogsInstance
      name: grafana-agent-logs
      version: v1alpha1
  - patch: |-
      - op: replace
        path: /spec/metrics/externalLabels/cluster
        value: "develop"
    target:
      kind: GrafanaAgent
      name: grafana-agent
      version: v1alpha1

  - path: cert-manager/patch-sealed-secret-email.yaml
  - path: mysql/patch-sealed-secret.yaml
  - path: monitoring/patch-sealedsecrets.yaml
