---
apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  labels:
    agent: grafana-agent
  name: grafana-agent-logs
spec:
  clients:
    - basicAuth:
        password:
          key: password
          name: logs-secret
        username:
          key: username
          name: logs-secret
      externalLabels:
        # Should be set in the overlays
        cluster: ""
      url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
  podLogsNamespaceSelector: {}
  podLogsSelector:
    matchLabels:
      instance: primary
