---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 2m0s
  dependsOn:
    - name: init
  sourceRef:
    kind: GitRepository
    name: m3d-k3s
  path: ./01_infrastructure/development
  prune: true
  timeout: 2m30s
  wait: true
