---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: init
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: m3d-k3s
  path: ./00_init/development
  prune: true
  timeout: 2m30s
  wait: true
