apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay includes .gitignored secrets which are initially applied to the cluster to bootstrap resources
# e.g. Sealed Secret keys or Git credentials for Flux.
# As the Secrets should still be managed by Sealed Secrets afterwards, the annotation 'sealedsecrets.bitnami.com/managed: "true"'
# is required.
resources:
  - ../development
  - namespace.yaml
  - secret/flux/secret-flux-ssh.yaml
  - secret/sealed-secrets/secret-sealed-secrets-key.yaml
