apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mariadb
spec:
  chart: mariadb
  version: ^11.0.0
  repo: https://charts.bitnami.com/bitnami
  set:
    auth.existingSecret: mariadb-passwords
  targetNamespace: mariadb
