---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: basic-auth-credentials
spec:
  template:
    apiVersion: "v1"
    kind: Secret
    metadata:
      name: basic-auth-credentials
    data:
      LOKI_BASIC_AUTH_PASSWORD:
        getValueFrom:
          kind: Secret
          name: grafana-agent-basic-auth-credentials
          namespace: flux-system
          path: "{.data.LOKI_BASIC_AUTH_PASSWORD}"
      PROMETHEUS_BASIC_AUTH_PASSWORD:
        getValueFrom:
          kind: Secret
          name: mysql-credentials
          namespace: mysql
          path: "{.data.PROMETHEUS_BASIC_AUTH_PASSWORD}"
