---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: basic-auth-credentials
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    # resourceNames: ["basic-auth-credentials"] # Doesn't seem to work with resourceNames :(
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: composable-basic-auth-credentials
subjects:
  - kind: ServiceAccount
    name: composable-controller-manager
    namespace: composable-system
roleRef:
  kind: Role
  name: basic-auth-credentials
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
  - kind: ServiceAccount
    name: grafana-agent
