---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: <2.0.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Set sane Cloudflare defaults
    extraArgs:
      - --cloudflare-dns-records-per-page=500
    policy: sync
    provider: cloudflare
    registry: txt
    sources:
      - ingress
    txtOwnerId: m3d-k3s/external-dns-default
    txtPrefix: _external-dns-default.
