---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    # Values are set in overlays
    CF_API_TOKEN: ""
    EXTERNAL_DNS_DOMAIN_FILTER: ""
    EXTERNAL_DNS_ZONE_ID_FILTER: ""
