apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # As Composable currently does not have the manifests and CRDs separated, this was done manually
  - crd-composable.yaml

  # Cert Manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
  # DB Operator
  - https://raw.githubusercontent.com/kloeckner-i/charts/db-operator-1.3.0/charts/db-operator/crds/kci.rocks_databases.yaml
  - https://raw.githubusercontent.com/kloeckner-i/charts/db-operator-1.3.0/charts/db-operator/crds/kci.rocks_dbinstances.yaml
  # Flux
  # - github.com/fluxcd/flux2/manifests/crds/?ref=v0.35.0
  # MySQL Operator
  - https://raw.githubusercontent.com/mysql/mysql-operator/8.0.31-2.0.7/deploy/deploy-crds.yaml
  # Sealed Secrets
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/v0.19.1/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
