---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/composable-operator/composable/releases/download/v0.3.1/crds.yaml

  # Cert Manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml

  # DB Operator includes its CRDs since v1.10.0
  - https://raw.githubusercontent.com/kloeckner-i/charts/db-operator-1.5.1/charts/db-operator/crds/kci.rocks_databases.yaml
  - https://raw.githubusercontent.com/kloeckner-i/charts/db-operator-1.5.1/charts/db-operator/crds/kci.rocks_dbinstances.yaml

  # MySQL Operator
  - https://raw.githubusercontent.com/mysql/mysql-operator/8.0.33-2.0.9/deploy/deploy-crds.yaml
  # Prometheus Operator
  #- https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.60.1/stripped-down-crds.yaml
  # Sealed Secrets
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/v0.19.1/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml

  # # Grafana-Operator
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_podmonitors.yaml?ref=grafana-agent-operator-0.2.10
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_probes.yaml?ref=grafana-agent-operator-0.2.10
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_servicemonitors.yaml?ref=grafana-agent-operator-0.2.10
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_grafanaagents.yaml?ref=grafana-agent-operator-0.2.10
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_integrations.yaml?ref=grafana-agent-operator-0.2.10
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_logsinstances.yaml?ref=grafana-agent-operator-0.2.10
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_metricsinstances.yaml?ref=grafana-agent-operator-0.2.10
  - https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_podlogs.yaml?ref=grafana-agent-operator-0.2.10

patches:
  - patch: |-
      - op: remove
        path: /metadata/creationTimestamp
    target:
      kind: CustomResourceDefinition
      name: composables.ibmcloud.ibm.com
