---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./03_clusters/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: m3d-k3s
