---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: db-operator

resources:
  - composable-mysql-root-credentials.yaml
  - dbinstance.yaml
  - helmrelease.yaml
  - namespace.yaml
  - rbac.yaml
