---
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: develop
servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.24.4-k3s1
options:
  k3d:
    wait: true
    timeout: "60s"
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
volumes:
  - volume: "${K3D_DIRECTORY}/manifests:/var/lib/rancher/k3s/server/manifests/"
    nodeFilters:
      - all
  - volume: "${K3D_DIRECTORY}/storage/:/var/lib/rancher/k3s/storage"
    nodeFilters:
      - all
