---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-state-metrics
      version: ^4.26.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
