---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/
  - flux/flux-kustomization.yaml
  - flux/git-repository.yaml

patches:
  - path: flux/patch-sealedsecret.yaml
